apiVersion: apps/v1
kind: Deployment
metadata:
  name: otherbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: otherbook
  template:
    metadata:
      labels:
        app: otherbook
    spec:
      containers:
      - image: nginx
        name: otherbook
        ports:
        - containerPort: 80
